### ISSUE TITLE
Klasni i MVC Dijagram

### ISSUE THREAD

**Issue by ibecir** [nkadric1/ProjekatOOAD#40]
1. Nema metoda (funkcija u klasnom dijagramu)
2. Relacije su 1 - *. Nemamo nigdje 0...* ili 1...* sto je vrlo bitno jer nam govori da li se moze desiti da ima taj entitet bez ovog osnovnog entiteta. 
3. U MVC dijagramu ne predstavljate rute u kontrolerima a to je obavezno jer je cilj ovog dijagrama da bude replika vaseg stvarnog stanja u kod. Mislim da imate previse kontrolera, ne mislim da cete ih trebati bas sve jer cete u nekim kontrolerima kombinovati entitete. Takodjer nemate sve poglede koji su vezani za kontroler (pogledi trebaju biti prazni ali kontroleri moraju da imaju sve rute koje postoje)

**Comment by nkadric1** [comment]
![MVCdiagram](https://github.com/nkadric1/ProjekatOOAD/assets/115932216/56ec9e15-8f9c-436b-8235-2b25b2f905a3)
- issue fixed @ibecir

**Comment by ibecir** [comment]
Puno bolje samo par stvari:
1. Playlist -> Song - nek kardinalnost ide od 1...* -> 1...* (razmisliti mozda moze biti playlista bez pjesama, npr: tek smo naravili playlistu pa cemo onda dodavati pjesme)
2. Song -> Editor - da li je relacija ispravna jedna pjesma moze imati vise editora a jedan editor samo jednu pjesmu? Nisam siguran da je ispravno al vi bolje znate na sta mislite samo razmislite da li je to dobra kardinalnost
3. Slicna situacija je RegisteredUser -> Song

Generalno uvijek stavljajte 0...* ili 1...*, iako * znaci od 0...* kad se cita sam dijagram zna biti malo zbunjujuce

**Comment by ibecir** [comment]
Sto se tice MVC dijagrama cini se super

**Comment by unahodzic1** [comment]
Što se tiče klasnog dijagrama, ovo je bila naša logika: 
1. Kardinalnost veze Playlist -> Song je 0..* -> 1..* jer jedna pjesma može biti u 0 ili više playlisti a playlista ne može postojati bez pjesme, dakle ne možemo napraviti playlistu koja će biti prazna pa u nju naknadno dodavati pjesme. 
2. i 3. Jedan korisnik može u jednom trenutku slušati samo jednu pjesmu, zbog toga smo stavile kardinalnost 0..* -> 1 za vezu RegisteredUser -> Song, slično i za vezu Editor -> Song jer jedan editor u jednom trenutku može uređivati samo jednu pjesmu, ali ukoliko naš način razmišljanja nije ispravan promijenit ćemo kardinalnost u tim slučajevima.
Ostale greške su ispravljene @ibecir 
![Class_diagram_final](https://github.com/nkadric1/ProjekatOOAD/assets/122841109/041e3e6d-18c6-4dc0-ae0b-4bd14836b45f)
