### ISSUE TITLE
Dijagram sekvenci

### ISSUE THREAD

**Issue by ibecir** [nkadric1/ProjekatOOAD#49]
1. Payload nije poslan na update  playlist
2. Dodati dio validacije pjesme (sta ako name nije validan)

**Comment by amilakukic** [comment]
![SequenceDiagram](https://github.com/nkadric1/ProjekatOOAD/assets/127833833/3101afb0-728d-43b1-a8f6-0ce3fd982d1f)

Nova verzija dijagrama sekvenci @ibecir
