### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ibecir** [nkadric1/ProjekatOOAD#56]
1. AspNetUser klase nema ER dijagramu 
2. Urediti pattern dokumente tako da ima jasan klasni dijagram implementacije odredjenog patterna kako bismo prepoznali potencijalne nedostatke na vrijeme a ne kad bude odbrana projekta.

**Comment by unahodzic1** [comment]
Klasni dijagrami za kreacijske paterne ispravljeni i urađeni po uzoru na dijagrame iz predavanja. 
Prototype patern:
[
![image](https://github.com/nkadric1/ProjekatOOAD/assets/122841109/b877f94f-c336-448b-9426-cae213be5234)
](url)

Singleton patern:
[
![image](https://github.com/nkadric1/ProjekatOOAD/assets/122841109/80505cc4-cb0a-47be-864b-1ae9082092e4)
](url)

@ibecir

**Comment by ibecir** [comment]
Odlicno
