### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ibecir** [nkadric1/ProjekatOOAD#57]
1. Za strukturalne patterne dodati i dijagram klasa onih patterna koji ce se implementirati kako bismo na vrijeme vidjeli da li je sve uredu sa patternom a ne za vrijeme odbrane projekta
2. Dijagram interakcije nije dobar, aktivacije su razdvojene a trebalo bi biti zajednom za odredjene stvari, raspravit cemo za vrijeme vjezbi

**Comment by ibecir** [comment]
Fali ER dijagram

**Comment by nkadric1** [comment]
Poštovani, ER dijagram se nalazi u  folderu Task 9 a također mi nemamo aktivacije u dijagramu interakcije. Nadam se da nije došlo do zabune.
